#!/bin/bash

set -e

usage() {
  cat <<EOF
Usage: $(basename "$0") [profile] [-c config] [-n name] [-l]
EOF
  exit 1
}

die() {
  local msg=$1
  echo "$msg" >&2
  exit 1
}

start_or_attach() {
  local tmuxp=$1
  local config=$2

  $tmuxp load -y "$config"
}

list_profiles() {
  find -L "$1" -name '*.json' -exec basename {} .json \;
}

tmuxp=$(command -v tmuxp)
[ -x "$tmuxp" ] || die 'tmuxp not found or not executable'

config_dir=$HOME/.tmuxp
session_name=$(basename "$PWD")

while getopts 'c:n:hl' opt; do
  case $opt in
    c)
      config_dir=$OPTARG
      ;;
    n)
      session_name=$OPTARG
      ;;
    l)
      list_profiles "$config_dir"
      exit
      ;;
    h|*)
      usage
      ;;
  esac
done

shift $((OPTIND - 1))

profile="${1:-default}"

config="$config_dir/$profile.json"

if [ -n "$session_name" ]; then
  export SESSION_NAME="$session_name"
fi

[ -d "$config_dir" ] || die "Configuration directory $config_dir does not exist"
[ -e "$config" ] || die "Could not find profile $profile"
[ -z "$TMUX" ] || die 'Already in a tmux session'

start_or_attach "$tmuxp" "$config"

exit
