#!/bin/bash

set -exu

BINDIR=$HOME/bin

do_install() {
  [ -d "$BINDIR" ]        || mkdir "$BINDIR"
  [ -e "$BINDIR/godeps" ] || ln -s "$PWD/godeps" "$BINDIR/godeps"
  [ -x "$BINDIR/godeps" ] || chmod +x "$BINDIR/godeps"
}

do_uninstall() {
  [ -e "$BINDIR/godeps" ] && rm "$BINDIR/godeps"
}

action=do_install
while getopts 'u' opt; do
  case $opt in
    u)
      action=do_uninstall
      ;;
    *)
      ;;
  esac
done

shift $((OPTIND - 1))

$action

exit $?
