#!/bin/bash

set -eu

HOST_PORT=8080
ACTION=run_web

usage() {
    cat <<EOF
Usage: `basename $0` [-p port] [stop] [name]
EOF
    exit 1
}

run_web() {
    local name=$1
    docker run \
           -d \
           -p $HOST_PORT:80 \
           -v $(pwd):/usr/share/nginx/html \
           --name "$name" \
           nginx
}

stop_web() {
    docker stop $1 >/dev/null && docker rm $1 >/dev/null
}

while getopts 'p:' opt; do
    case $opt in
        p)
            HOST_PORT=$OPTARG
            ;;
        *)
            usage
            ;;
    esac
done

shift $((OPTIND - 1))

# First argument is hopefully 'stop'
if [ "${1:-}" == stop ]; then
    ACTION=stop_web
    shift
fi

name="${1:-$(basename `pwd`)}"

$ACTION $name

exit $?
