#!/bin/bash

set -eu

HOST_PORT=8080
ACTION=run_web

usage() {
    cat <<EOF
Usage: `basename $0` [-p port] [stop|list] [name]
EOF
    exit 1
}

run_web() {
    local name="${1}-web"
    docker run \
           -d \
           -p $HOST_PORT:80 \
           -v $(pwd):/usr/share/nginx/html \
           --name "$name" \
           nginx
}

stop_web() {
    local name="${1}-web"
    docker stop $name >/dev/null && docker rm $name >/dev/null
}

list_web() {
    {
        echo 'ID Port Name'
        echo '-- ---- ----'
        docker ps | \
            grep -- '-web' | \
            awk '{ print $1, $(NF - 1), $NF }' | \
            sed -e 's/0\.0\.0\.0://' -e 's|\->80/tcp||'
    } | column -t
}

while getopts 'p:' opt; do
    case $opt in
        p)
            HOST_PORT=$OPTARG
            ;;
        *)
            usage
            ;;
    esac
done

shift $((OPTIND - 1))

action="${1:-}"

case $action in
    stop)
        ACTION=stop_web
        shift
        ;;
    list)
        ACTION=list_web
        shift
        ;;
esac

name="${1:-$(basename `pwd`)}"
name="${name//-web/}"

$ACTION $name

exit $?
